import type { AdmissionSource } from '../../core/sourceRegistry';

export const qnuSources: (Omit<AdmissionSource, 'schoolId'> & { note?: string })[] = [
  {
    id: 'qnu-threshold-2025',
    publisher: 'Trangedu.com (tường thuật thông báo chính thức Trường Đại học Quy Nhơn)',
    title: 'Điểm chuẩn trúng tuyển trường Đại học Quy Nhơn 2025',
    url: 'https://trangedu.com/diem-chuan/diem-chuan-dai-hoc-quy-nhon/',
    accessedAt: '2026-09-02',
    publishedAt: '2025-08-22',
    sourceType: 'secondary',
    verification: 'verified',
    lifecycle: { effectiveYear: 2025, status: 'current' },
    note:
      'Bảng điểm chuẩn đầy đủ 52+ ngành đại học chính quy, phương thức xét kết quả thi TN THPT 2025, kèm mã ngành và tổ hợp môn. Batch này chỉ dùng 10/52 ngành khối sư phạm/giáo dục (không nhân hệ số môn chính — tránh nhóm ngành Kinh tế/Kỹ thuật nơi 2 nguồn cross-check lệch nhau): Sư phạm Lịch sử (7140218) 27,21; Giáo dục Tiểu học (7140202) 26,90; Sư phạm Ngữ văn (7140217) 26,85; Sư phạm Địa lý (7140219) 26,74; Giáo dục chính trị (7140205) 26,65; Sư phạm Toán học (7140209) 25,85; Sư phạm Hóa học (7140212) 25,30; Quản lý Giáo dục (7140114) 25,10; Sư phạm Vật lý (7140211) 24,40; Sư phạm Tiếng Anh (7140231) 23,59 (thang 30).',
  },
  {
    id: 'qnu-threshold-secondary-2025',
    publisher: 'Sforum / CellphoneS (tường thuật thông báo chính thức Trường Đại học Quy Nhơn)',
    title: 'Điểm chuẩn Đại học Quy Nhơn 2025',
    url: 'https://cellphones.com.vn/sforum/diem-chuan-dai-hoc-quy-nhon-2025',
    accessedAt: '2026-09-02',
    publishedAt: '2025-08-22',
    sourceType: 'secondary',
    verification: 'verified',
    lifecycle: { effectiveYear: 2025, status: 'current' },
    note:
      'Cross-check độc lập với `qnu-threshold-2025` (trangedu) — khớp số liệu tuyệt đối cho 9/10 ngành đã mô hình hoá: Giáo dục Tiểu học 26,9; Sư phạm Ngữ văn 26,85; Giáo dục Chính trị 26,65; Sư phạm Địa lý 26,74; Quản lý Giáo dục 25,1; Sư phạm Toán 25,85; Sư phạm Hóa 25,3; Sư phạm Vật lý 24,4; Sư phạm Tiếng Anh 23,59. Trích nguyên văn công thức: "ĐXT = (Điểm môn 1) + (Điểm môn 2) + (Điểm môn 3) + (Điểm ưu tiên)" kèm ghi chú "Các ngành có nhân hệ số môn chính được quy đổi về thang 30 trước xét tuyển" — GHI CHÚ QUAN TRỌNG dùng để loại các ngành khối Kinh tế/Kỹ thuật (Kinh tế: nguồn này 22,15 vs trangedu 21,4; CNTT: 21,85 vs 21,5 — LỆCH NHAU, không đủ tin cậy, không mô hình hoá).',
  },
  {
    id: 'qnu-threshold-tertiary-2025',
    publisher: 'Báo Gia Lai điện tử',
    title: 'Trường Đại học Quy Nhơn: Điểm chuẩn ngành Sư phạm Lịch sử cao nhất với 27,21 điểm',
    url: 'https://baogialai.com.vn/truong-dai-hoc-quy-nhon-diem-chuan-nganh-su-pham-lich-su-cao-nhat-voi-2721-diem-post564498.html',
    accessedAt: '2026-09-02',
    publishedAt: '2025-08-22',
    sourceType: 'secondary',
    verification: 'verified',
    lifecycle: { effectiveYear: 2025, status: 'current' },
    note: 'Cross-check độc lập thứ 3, riêng cho Sư phạm Lịch sử — khớp 27,21/30 với cả trangedu và Sforum.',
  },
  {
    id: 'qnu-admission-scheme-2025',
    publisher: 'Tuyensinh247 (đăng lại đề án tuyển sinh Trường Đại học Quy Nhơn)',
    title: 'Cập nhật điểm chuẩn Đại học Quy Nhơn 2025 mới nhất theo ngành và phương thức xét tuyển',
    url: 'https://viettelstore.vn/tin-tuc/cap-nhat-diem-chuan-dai-hoc-quy-nhon-2025-moi-nhat-theo-nganh-va-phuong-thuc-xet-tuyen',
    accessedAt: '2026-09-02',
    sourceType: 'secondary',
    verification: 'verified',
    lifecycle: { effectiveYear: 2025, status: 'current' },
    note: '52 ngành đào tạo đại học, điểm chuẩn dao động từ 15 đến 27,21 điểm — dùng để xác nhận phạm vi tổng thể (min/max) khớp với `qnu-threshold-2025`.',
  },
  {
    id: 'qnu-official-portal-2025',
    publisher: 'Cổng Thông tin điện tử Chính phủ',
    title: 'Điểm chuẩn Trường Đại học Quy Nhơn 2025',
    url: 'https://xaydungchinhsach.chinhphu.vn/diem-chuan-truong-dai-hoc-quy-nhon-2025-1192508231044467.htm',
    accessedAt: '2026-09-02',
    publishedAt: '2025-08-23',
    sourceType: 'government',
    verification: 'incomplete',
    lifecycle: { effectiveYear: 2025, status: 'current' },
    note: 'Trang xác nhận đã đăng thông báo điểm chuẩn chính thức của trường nhưng bảng số liệu chỉ hiển thị dạng ẢNH — không trích xuất được bằng text extraction thông thường. KHÔNG dùng làm nguồn số liệu chính, chỉ liệt kê để tham chiếu.',
  },
];
